baseURL = "/"
languageCode = "ko-kr"
DefaultContentLanguage = "ko"
title = "Dev Blog"
theme = "docdock"
pygmentsCodeFences = true
pygmentsStyle = "monokailight"

[outputs]
home = [ "HTML", "RSS", "JSON"]

[params]
showVisitedLinks = true # default is false

[[menu.shortcuts]]
pre = "<h3>More</h3>"
name = "<i class='fa fa-github'></i> <label>Github repo</label>"
identifier = "ds"
url = "https://github.com/yangbongsoo"
weight = 10
